### PR TITLE
Features basic page structure

### PR DESCRIPTION
**Pull request by afcastaneda223**
# Documentation

All the documentation is on the README file.

## Updates:

- Simple HTML for a form of name and scores
- Add new list elements with input from the user

## Notes:

Coded by @afcastaneda223

✅  - No linters errors were detected.

### CODE REVIEW

**Review by mricanho — CHANGES_REQUESTED** [review]
Hi @afcastaneda223, 

Good job so far! Everything looks fine, just a minor detail with the linters🔥🔥

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] Now that you are fully in the JavaScript module you need to use just the configuration for JS, [here's the link](https://github.com/microverseinc/linters-config/tree/master/javascript), easy fix.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

almostthere

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by afcastaneda223** [comment]
sure, that makes sense but I used the  HTML, CSS, JS linters which also includes JavaScript  https://github.com/microverseinc/linters-config/tree/master/html-css-js 

isn't that better?

**Comment by afcastaneda223** [comment]
Screen Shot 2021-07-27 at 11 13 34 PM

As you can see on the screenshot it actually runs the tests that you are requesting.

**Comment by mricanho** [comment]
> Screen Shot 2021-07-27 at 11 13 34 PM
> 
> As you can see on the screenshot it actually runs the tests that you are requesting.

Hi @afcastaneda223!

There are few changes from one version to another, in the JS module, most of the work is happening in Index.js, and HTML would be empty, which will make errors in lighthouse and webhint, so it's better to remove them.

**Review by hemantso — CHANGES_REQUESTED** [review]
Hi @afcastaneda223, 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Alt Text
 ## Required Changes ♻️

- [ ] As suggested by the previous review, in the JS module, most of the work is happening in Index.js, and HTML would be empty, which will make errors in lighthouse and webhint, so it's better to remove them. you need to use just the configuration for JS. Kindly try to make changes as requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers,
Hemant Soni
Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by hemantso — APPROVED** [review]
Hi @afcastaneda223, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

Alt Text

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
